name: emergenshare
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  web_scraper: ^0.1.4
  beautiful_soup_dart: ^0.2.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutterfire_ui: ^0.3.5+1
  flutter_rating_bar: ^4.0.0
  emoji_picker_flutter: ^1.1.2
  chips_choice: ^2.0.1
  flutter_html: ^3.0.0-alpha.3
  shared_preferences: ^2.0.13



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  getwidget: ^2.0.5
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  cloud_firestore: ^3.1.10
  auto_size_text: ^3.0.0
  settings_ui: ^2.0.2
  url_launcher: ^6.0.20
  flutter_email_sender: ^5.1.0
  image_picker: ^0.8.4+10

flutter:
  uses-material-design: true
  assets:
    - lib/components/assets/images/illustration/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
