// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRvTWD5eltuK-TcMq2WVU208mrrAFfVdU',
    appId: '1:673378477012:web:39db20b224cd73944a6c41',
    messagingSenderId: '673378477012',
    projectId: 'emergenshare',
    authDomain: 'emergenshare.firebaseapp.com',
    storageBucket: 'emergenshare.appspot.com',
    measurementId: 'G-B97TYZBNJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1AfYuX65ZoyCJAaTezEhpzhcBmPXys6M',
    appId: '1:673378477012:android:263072a8e98dd4ae4a6c41',
    messagingSenderId: '673378477012',
    projectId: 'emergenshare',
    storageBucket: 'emergenshare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHeV3oasm1n4Hr5S4qSBhHGPH78E1WOtc',
    appId: '1:673378477012:ios:976696abf934187b4a6c41',
    messagingSenderId: '673378477012',
    projectId: 'emergenshare',
    storageBucket: 'emergenshare.appspot.com',
    iosClientId: '673378477012-rbc904v66m627ivpp3o1c8jdu1h3qtml.apps.googleusercontent.com',
    iosBundleId: 'com.emergenshare.emergenshare',
  );
}
